# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(470, 337)
        LoginDialog.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.256, y1:0.210227, x2:0.858, y2:0.829864, stop:0 rgba(0, 0, 255, 255), stop:1 rgba(255, 255, 0, 255));")
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_login_titulo = QtWidgets.QLabel(LoginDialog)
        self.lbl_login_titulo.setStyleSheet("    background-color: transparent;\n"
"    border: none;")
        self.lbl_login_titulo.setObjectName("lbl_login_titulo")
        self.verticalLayout.addWidget(self.lbl_login_titulo)
        self.frame_login_acao = QtWidgets.QFrame(LoginDialog)
        self.frame_login_acao.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_login_acao.setAutoFillBackground(False)
        self.frame_login_acao.setStyleSheet("    background-color: transparent;\n"
"    border: none; /* Opcional: remove a borda também */")
        self.frame_login_acao.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_login_acao.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_login_acao.setObjectName("frame_login_acao")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_login_acao)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_login_info = QtWidgets.QFrame(self.frame_login_acao)
        self.frame_login_info.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_login_info.setStyleSheet("    background-color: transparent;\n"
"    border: none; /* Opcional: remove a borda também */")
        self.frame_login_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_login_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login_info.setObjectName("frame_login_info")
        self.formLayout = QtWidgets.QFormLayout(self.frame_login_info)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.lbl_login_email = QtWidgets.QLabel(self.frame_login_info)
        self.lbl_login_email.setObjectName("lbl_login_email")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_login_email)
        self.edit_login_email = QtWidgets.QLineEdit(self.frame_login_info)
        self.edit_login_email.setMinimumSize(QtCore.QSize(0, 20))
        self.edit_login_email.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;")
        self.edit_login_email.setObjectName("edit_login_email")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_login_email)
        self.edit_login_senha = QtWidgets.QLineEdit(self.frame_login_info)
        self.edit_login_senha.setMinimumSize(QtCore.QSize(0, 20))
        self.edit_login_senha.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.edit_login_senha.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;\n"
"")
        self.edit_login_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edit_login_senha.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.edit_login_senha.setObjectName("edit_login_senha")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_login_senha)
        self.lbl_login_senha = QtWidgets.QLabel(self.frame_login_info)
        self.lbl_login_senha.setObjectName("lbl_login_senha")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_login_senha)
        self.verticalLayout_2.addWidget(self.frame_login_info)
        self.frame_login_btns = QtWidgets.QFrame(self.frame_login_acao)
        self.frame_login_btns.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_login_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_login_btns.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_login_btns.setObjectName("frame_login_btns")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_login_btns)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_login_btn_in = QtWidgets.QFrame(self.frame_login_btns)
        self.frame_login_btn_in.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login_btn_in.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login_btn_in.setObjectName("frame_login_btn_in")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_login_btn_in)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_login_entrar = QtWidgets.QPushButton(self.frame_login_btn_in)
        self.btn_login_entrar.setMinimumSize(QtCore.QSize(0, 20))
        self.btn_login_entrar.setMouseTracking(True)
        self.btn_login_entrar.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 8px")
        self.btn_login_entrar.setObjectName("btn_login_entrar")
        self.horizontalLayout.addWidget(self.btn_login_entrar)
        self.btn_login_sair = QtWidgets.QPushButton(self.frame_login_btn_in)
        self.btn_login_sair.setMinimumSize(QtCore.QSize(0, 20))
        self.btn_login_sair.setMouseTracking(True)
        self.btn_login_sair.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.btn_login_sair.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 8px")
        self.btn_login_sair.setObjectName("btn_login_sair")
        self.horizontalLayout.addWidget(self.btn_login_sair)
        self.verticalLayout_3.addWidget(self.frame_login_btn_in)
        self.frame_login_esqueceu = QtWidgets.QFrame(self.frame_login_btns)
        self.frame_login_esqueceu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login_esqueceu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login_esqueceu.setObjectName("frame_login_esqueceu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_login_esqueceu)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_login_esqueceu = QtWidgets.QPushButton(self.frame_login_esqueceu)
        self.btn_login_esqueceu.setMinimumSize(QtCore.QSize(0, 20))
        self.btn_login_esqueceu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_login_esqueceu.setMouseTracking(True)
        self.btn_login_esqueceu.setStyleSheet("color: rgb(0, 85, 255);")
        self.btn_login_esqueceu.setObjectName("btn_login_esqueceu")
        self.verticalLayout_4.addWidget(self.btn_login_esqueceu)
        self.verticalLayout_3.addWidget(self.frame_login_esqueceu)
        self.verticalLayout_2.addWidget(self.frame_login_btns)
        self.verticalLayout.addWidget(self.frame_login_acao)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Login"))
        self.lbl_login_titulo.setText(_translate("LoginDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">LOGIN SISTEMA DE GESTÃO DE FROTA</span></p></body></html>"))
        self.lbl_login_email.setText(_translate("LoginDialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">E-MAIL:</span></p></body></html>"))
        self.lbl_login_senha.setText(_translate("LoginDialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">SENHA:</span></p></body></html>"))
        self.btn_login_entrar.setText(_translate("LoginDialog", "ENTRAR"))
        self.btn_login_sair.setText(_translate("LoginDialog", "SAIR"))
        self.btn_login_esqueceu.setText(_translate("LoginDialog", "ESQUECEU A SENHA?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginDialog = QtWidgets.QDialog()
    ui = Ui_LoginDialog()
    ui.setupUi(LoginDialog)
    LoginDialog.show()
    sys.exit(app.exec_())
